Complex derivative1
codereckons/fluxion pull request #17
Opened 2022-12-10 19:44 UTC by jtlap

2022-12-10 19:47 UTC, jfalcou requested changes

2022-12-10 19:47 UTC, jfalcou commented on test/unit/module/derivative/math/cos.cpp
> +  //  eve::as_complex_t<T> z(a0, a1);
remove cout and write a real test

2022-12-10 19:47 UTC, jfalcou commented on test/cmeasures.hpp
> +  EVE - Expressive Vector Engine
fix licence header

2022-12-10 19:47 UTC, jfalcou commented on include/flx/derivative/module/special/tgamma.hpp
> +  template<value T>
not ordered ?

2022-12-10 19:47 UTC, jfalcou commented on include/flx/derivative/module/special/lbeta.hpp
> +  template<value T>
don't reindent for nothing

2022-12-10 20:22 UTC, jtlap commented on include/flx/derivative/module/special/tgamma.hpp
> +  template<value T>
for complex

2022-12-10 20:25 UTC, jtlap commented on test/cmeasures.hpp
> +  EVE - Expressive Vector Engine
c'est le seul test complex et je l'avais oublié. je fais

2022-12-10 20:29 UTC, jtlap commented on include/flx/derivative/module/special/lbeta.hpp
> +  template<value T>
ok mais je préférerait qu'on ralonge les lignes de 10 caractères et qu'on indente dans les namespace

2022-12-11 08:47 UTC, jfalcou approved these changes

2022-12-11 08:47 UTC, merged